name: Exact versions

on:
  push:
    branches:
      - '**'
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: yarn add @actions/core -E

      - name: Check exact versions
        uses: ./.github/actions/check-version-lock
