name: Publish version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      STX_NETWORK: ${{ matrix.stx_network }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        stx_network: [testnet, mainnet]
        include:
          - os: macos-latest
            NPM_COMMAND: mac

          - os: ubuntu-latest
            NPM_COMMAND: linux

          - os: windows-latest
            NPM_COMMAND: win

    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Variables
        id: vars
        run: |
          echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=pull_request_id::$(echo $GITHUB_REF)"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      #
      # Windows build breaks when using the package.json script to install `app/` packages
      # using separate run to install those packages separately
      - name: Install packages
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Install `app/` packages
        run: cd app && yarn --frozen-lockfile --ignore-scripts

      - name: Build releases
        run: ./node_modules/.bin/cross-env yarn package-${{ matrix.NPM_COMMAND }}
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ steps.vars.outputs.pull_request_id }}
          BRANCH_NAME: ${{ steps.vars.outputs.branch_name }}
          WALLET_VERSION: ${{ steps.extract_version.outputs.version }}

      - uses: actions/upload-artifact@v2
        name: Windows upload
        if: matrix.os == 'windows-latest'
        with:
          name: stacks-wallet-${{ matrix.stx_network }}-${{ matrix.NPM_COMMAND }}
          path: |
            release/**/*.exe
            release/**/*.msi

      - uses: actions/upload-artifact@v2
        name: MacOS upload
        if: matrix.os == 'macos-latest'
        with:
          name: stacks-wallet-${{ matrix.stx_network }}-${{ matrix.NPM_COMMAND }}
          path: release/**/*.dmg

      - uses: actions/upload-artifact@v2
        name: Linux upload
        if: matrix.os == 'ubuntu-latest'
        with:
          name: stacks-wallet-${{ matrix.stx_network }}-${{ matrix.NPM_COMMAND }}
          path: |
            release/**/*.deb
            release/**/*.rpm

  create-release-mainnet:
    runs-on: ubuntu-latest
    needs:
      - build

    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: Release v${{ needs.build.outputs.version }}
          draft: false
          prerelease: ${{contains(needs.build.outputs.version, 'beta')}}

  create-release-testnet:
    runs-on: ubuntu-latest
    needs:
      - build

    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: '[Testnet] v${{ needs.build.outputs.version }}'
          draft: false
          prerelease: ${{ contains(needs.build.outputs.version, 'beta')} }

  publish-assets-mainnet:
    runs-on: ubuntu-latest
    needs:
      - build
      - create-release-mainnet

    strategy:
      matrix:
        include:
          - ext: dmg
            os: mac
          - ext: msi
            os: win
          - ext: rpm
            os: linux
          - ext: deb
            os: linux

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          path: release/

      - run: ls -R release

      - name: Upload Release Asset .${{ matrix.ext }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release-mainnet.outputs.release_upload_url }}
          asset_path: release/stacks-wallet-${{ matrix.os }}/stacks-wallet.mainnet.${{ matrix.ext }}
          asset_name: stacks-wallet.testnet.v${{ needs.build.outputs.version }}.${{ matrix.ext }}
          asset_content_type: application/octet-stream

  publish-assets-testnet:
    runs-on: ubuntu-latest
    needs:
      - build
      - create-release-testnet

    strategy:
      matrix:
        include:
          - ext: dmg
            os: mac
          - ext: msi
            os: win
          - ext: rpm
            os: linux
          - ext: deb
            os: linux

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          path: release/

      - run: ls -R release

      - name: Upload Release Asset .${{ matrix.ext }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release-testnet.outputs.release_upload_url }}
          asset_path: release/stacks-wallet-${{ matrix.os }}/stacks-wallet.testnet.${{ matrix.ext }}
          asset_name: stacks-wallet.testnet.v${{ needs.build.outputs.version }}.${{ matrix.ext }}
          asset_content_type: application/octet-stream

  announce-release:
    runs-on: ubuntu-latest
    needs:
      - build
      - create-release-mainnet
      - create-release-testnet
      - publish-assets-mainnet
      - publish-assets-testnet

    if: always()
    steps:
      - name: Discord notification
        # Only run if a new release was published
        if: needs.release.outputs.new_release_published == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
           New release: Stacks Wallet `v${{needs.release.outputs.new_release_version}}`.
           [Download mainnet build](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.build.outputs.version }})).
           Download testnet build.

           A new version ([v${{needs.release.outputs.new_release_version}}](https://github.com/${{ github.repository }}/releases/tag/v${{needs.release.outputs.new_release_version}})) of the ${{ github.workflow }} has been released.
