name: Publish version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      STX_NETWORK: ${{ matrix.stx_network }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        stx_network: [testnet, mainnet]
        include:
          - os: macos-latest
            UPLOAD_ASSETS: release/**/*.dmg
            NPM_COMMAND: mac


          - os: ubuntu-latest
            NPM_COMMAND: linux
            UPLOAD_ASSETS: |
              release/**/*.deb
              release/**/*.rpm

          - os: windows-latest
            NPM_COMMAND: win
            UPLOAD_ASSETS: release/**/*.exe


    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Variables
        id: vars
        run: |
          echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=pull_request_id::$(echo $GITHUB_REF)"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      #
      # Windows build breaks when using the package.json script to install `app/` packages
      # using separate run to install those packages separately
      - name: Install packages
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 600
          max_attempts: 3
          retry_on: error
          command: yarn --frozen-lockfile --ignore-scripts

      - name: Install `app/` packages
        run: cd app && yarn --frozen-lockfile --ignore-scripts

      - name: Install `concat-map` - Windows only
        run: yarn add concat-map --ignore-scripts --frozen-lockfile
        if: matrix.os == 'windows-latest'

      - name: Build releases
        run: ./node_modules/.bin/cross-env yarn package-${{ matrix.NPM_COMMAND }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          SHA: ${{ github.event.pull_request.head.sha }}
          PULL_REQUEST: ${{ steps.vars.outputs.pull_request_id }}
          BRANCH_NAME: ${{ steps.vars.outputs.branch_name }}

      - uses: actions/upload-artifact@v2
        name: ${{ matrix.os }} upload
        with:
          name: stacks-wallet-${{ matrix.stx_network }}-${{ matrix.NPM_COMMAND }}
          path: ${{ matrix.UPLOAD_ASSETS }}

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build

    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: Release v${{ needs.build.outputs.version }}
          draft: false
          prerelease: ${{ contains(needs.build.outputs.version, 'beta') }}

  upload-release-assets:
    runs-on: ubuntu-latest
    needs:
      - build
      - create-release

    strategy:
      max-parallel: 2
      matrix:
        stx_network: [testnet, mainnet]
        ext: [dmg, exe, deb, rpm]
        include:
          - ext: dmg
            os: mac
          - ext: exe
            os: win
          - ext: rpm
            os: linux
          - ext: deb
            os: linux

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          path: release

      - run: ls -R release

      - name: Upload Release Asset .${{ matrix.ext }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: release/stacks-wallet-${{ matrix.stx_network }}-${{ matrix.os }}/stacks-wallet.${{ matrix.stx_network }}.${{ matrix.ext }}
          asset_name: stacks-wallet.${{ matrix.stx_network }}.v${{ needs.build.outputs.version }}.${{ matrix.ext }}
          asset_content_type: application/octet-stream

  announce-release:
    runs-on: ubuntu-latest
    needs:
      - build
      - upload-release-assets

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🔔 New Stacks Wallet released: [Download `v${{ needs.build.outputs.version }}` here](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.build.outputs.version }})
