name: Release signatures

on:
  release:
    types: [published, edited]

jobs:
  make-signatures:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ job }}

      - run: echo ${{ toJSON(job) }}

      - name: Flatten assets to root dir
        run: find downloads -type f -depth 2 -exec mv '{}' . \; && rm -rf downloads

      - run: ls | xargs -I{} shasum -a 256 {} | tee -a shasum.txt

      - name: Import GPG key
        id: import_gpg_key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - run: gpg --armor --output shasum.txt.asc --clearsign shasum.txt

      - uses: actions/upload-artifact@v2
        with:
          name: shasum.txt.asc
          path: shasum.txt.asc
