name: Typecheck

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn
        env:
          STX_NETWORK: testnet

      - name: Build
        run: yarn tsc --noEmit
